<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZgWDwHa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZgWDwHa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZgWDwHa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZgWDwHa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZgWDwHa\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZgWDwHa',
    'container.build_id' => '242e040d',
    'container.build_time' => 1697734616,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZgWDwHa');
